Feature/water quality sensor
elifTech/school-project-2019 pull request #3
Opened 2019-10-09 16:47 UTC by ArtemOliinyk

2019-10-15 16:37 UTC, undead404 requested changes

2019-10-15 16:37 UTC, undead404 commented on client/package.json
> +    "chart.js": "^2.8.0",
Use tilde notation please

2019-10-15 16:37 UTC, undead404 commented on client/src/components/Menu/index.js
> +        <div className={`${s.menuItems} ${isMenuOpen && s.menuItemsActive}`}>
use `classnames` library here please

2019-10-15 16:37 UTC, undead404 commented on client/src/components/Menu/index.js
> +            <svg
please extract your static SVGs to separate SVG files

2019-10-15 16:37 UTC, undead404 commented on client/src/components/Menu/index.js
> +  menuItems = [
maybe extract these items into a separate JSON file or separate JS file.

2019-10-16 14:19 UTC, undead404 requested changes

2019-10-16 14:19 UTC, undead404 commented on client/package.json
> +    "moment": "^2.24.0",
Please use tilde in stable dependencies

2019-10-16 14:19 UTC, undead404 commented on client/src/components/LineChart/LineChart.js
> +import style from '../WaterQualitySensor/WaterQualitySensor.css';
Do you really need to share these styles among components?

2019-10-16 14:19 UTC, undead404 commented on client/src/components/WaterQualitySensor/WaterQualitySensor.js
> +  loading = () => {
Please rename it to start with `render` word

2019-10-17 20:26 UTC, undead404 commented on client/src/components/WaterQualitySensor/WaterQualitySensor.js
> +                  onClick={dispatchChangeFilter(button.value)}
Hmmm, does this work?

2019-10-17 20:42 UTC, ArtemOliinyk commented on client/src/components/WaterQualitySensor/WaterQualitySensor.js
> +                  onClick={dispatchChangeFilter(button.value)}
It does, why not?

2019-10-21 07:48 UTC, undead404 approved these changes

2019-10-22 09:38 UTC, undead404 commented on server/go.mod
> +	github.com/jasonlvhit/gocron v0.0.0-20190920201010-985d45da66c5
Do you use gocron?

2019-10-22 09:40 UTC, merged